export const TOKEN = {
  user: "tplus-user-token",
  remember_login: "tplus-user-remember_login",
  permission_modal: "tplus-user-permission-modal",
  conn_begin_dt: "tplus-user-conn_begin_dt",

  build_type_txt: "development",
};

export const LinkInfo = {
  // 구글 플레이 스토어 링크
  GOOGLE_PLAY_STORE_LINK: 'market://details?id=com.kct.tplusmarket',
// 구글 플레이 스토어가 설치되어 있지 않을 때 웹 링크
  GOOGLE_PLAY_STORE_WEB_LINK:
      'https://play.google.com/store/apps/details?id=com.kct.tplusmarket',
// 애플 앱 스토어 링크
  APPLE_APP_STORE_LINK:
      'itms-apps://itunes.apple.com/kr/app/apple-store/id1599203902',
// 애플 앱 스토어가 설치되어 있지 않을 때 웹 링크
  APPLE_APP_STORE_WEB_LINK:
      'https://itunes.apple.com/kr/app/apple-store/id1599203902',
}

export const Generic = {
  home: "홈",
  store: "스토어",
  tag: "태그",
  mypage: "마이페이지",
  checkInput: "양식을 채워주세요.",
  confirm: "확인",
  cancel: "취소",
  finish: "완료",
  close: "닫기",
  edit: "수정",
  delete: "삭제",
  no: "아니요",
  loginMessage: "로그인이 필요한 서비스입니다.",
  goToLogin: "네, 로그인할게요.",
  callNumber: "1533-5040",
  notice: "알림",
  alertMessage: "서버점검 중이거나\n인터넷이 연결되어있지 않습니다.\n잠시 후 다시 시도해주세요",
  appVerMessage: "더 나은 서비스 이용을 위해 앱을 최신 버전으로 업데이트 해주세요.",
  goToUpdate: "업데이트",
};

export const TermsCode = {
  terms: "20211014220120A9STF1", // 약관 및 주요안내사항
  primary: "20211014220120A9STF2", // 개인정보 동의
  business: "20211014220120A9STF3", // 사업자 이용약관
  policy3rd: "20211014220120A9STF4", // 제 3자 제공 동의
  marketing: "20211014220120A9STF5", // 마케팅 활용동의
  selfTerms: "20211014220120A9STF6", // 본인확인 이용동의
  uniqueNumber: "20211014220120A9STF7", // 고유식별번호 처리 동의
  service: "20211014220120A9STF8", // 이통사별 서비스 이용약관
};

export const SocialKey = {
  // 소셜 로그인 키
  kakao_app_key: "2ab0de254783f5b8dbcd9f3711be01ae",
  kakao_scheme: "kakao2ab0de254783f5b8dbcd9f3711be01ae",

  naver_client_id: "CPPuCXea_g9Zg92ZvnSk",
  naver_client_secret: "FwHI_ASRsE",

  google_client_id: "664958004841-6dgses8asqnd5gqfr6hihfvqddvhsurh.apps.googleusercontent.com"
};

export const appScheme = {
  app_scheme: "KCTMARKET://kct.com",
  scheme: "KCTMARKET",
  host: "kct.com"
}

export const iosKeys = {
  // 네이버 스키마 설정
  kConsumerKey: SocialKey.naver_client_id,
  kConsumerSecret: SocialKey.naver_client_secret,
  kServiceAppName: "Tplus",
  kServiceAppUrlScheme: "naverkcttplusmarket",
};

export const androidKeys = {
  kConsumerKey: SocialKey.naver_client_id,
  kConsumerSecret: SocialKey.naver_client_secret,
  kServiceAppName: "Tplus",
};

export const LoginText = {
  general: "일반회원",
  business: "기업회원",
  generalCheckEmail: "이메일 양식이 맞지 않습니다.",
  generalPlaceHolder: "아이디(이메일 주소)를 입력해주세요.",
  businessPlaceHolder: "사업자등록번호를 입력해주세요('-'제외 입력)",
  passwordPlaceHolder: "비밀번호를 입력해주세요",
  login: "로그인",
  findEmail: "아이디찾기",
  findPassword: "비밀번호찾기",
  socialLogin: "간편한 SNS 로그인",
  signUp: "회원가입",
  signUpDesc: "서비스가 처음이세요?",
  headerText: "둘러보기",
};

export const SignupText = {
  signupGiveUp: "첫화면으로 이동",
  signupFirstPageMessage: "첫화면으로 이동하시겠습니까?",
  signupFirstPage: "네, 이동할래요.",
  signupFailErrorMessage: "회원가입에 실패하였습니다.\n고객센터로 문의해주세요",
  userType: "가입하실 회원유형을\n선택하세요",
  next: "다음",
  general: "일반회원",
  business: "기업회원",
  businessUser: "기업회원",
  terms: "약관동의가\n필요합니다.",
  fullConsent: "서비스 이용약관 전체 동의",
  mainInfo: "약관 및 주요안내사항",
  primary: "개인정보 동의",
  thirdParty: "제 3자 제공 동의",
  marketing: "마케팅 활용동의",
  seeMore: "보기",
  required: "(필수)",
  optional: "(선택)",
  inflow: "해당 서비스를\n어떻게 알게되셨나요?",
  account: "회원가입 정보가\n필요합니다.",
  idAuth: "본인확인을 위해\n인증이 필요합니다",
  businessIdAuth: "업체확인을 위해\n담당자 인증이 필요합니다",
  idAuthTerms: "본인 인증을 위한 개인정보 처리 전체 동의",
  idAuthDesc: "입력하신 정보와\n일치하는 아이디 정보입니다.",
  idAuthDescFail: "입력하신 정보와\n일치하는 아이디 정보가 없습니다.",
  findId: "아이디 찾기",
  findPwd: "비밀번호 찾기",
  id: "아이디",
  subscriptionDate: "가입일",
  accountTerms: "본인 확인을 위한 약관 동의",
  identification: "본인확인 이용동의",
  uniqueNumber: "고유식별번호 처리동의",
  service: "이통사별 서비스 이용약관",
  name: "이름: 반드시 실명으로 입력해주시기 바랍니다.",
  incorrectName: "* 이름은 1~10자 이내로 입력하셔야 합니다.",
  incorrectKorName: "* 이름은 한글로 입력하셔야 합니다.",
  birth: "생년월일 6자리",
  newsAgency: "통신사",
  requestAuth: "인증요청",
  reRequestAuth: "재인증요청",
  incorrectAuth: "인증번호가 올바르지 않습니다.",
  reSendVerification:
    "인증번호의 유효기간이 만료되었습니다.\n인증번호를 재발송해주세요.",
  number: "휴대폰번호: -없이 번호입력",
  numberCompany: "-없이 담당자 번호입력",
  authNumber: "인증번호 6자리 입력",
  requiredInfo: "필수 정보를\n입력하세요",
  email: "아이디(이메일) 입력",
  incorrectEmail: "* 올바르지 않은 이메일 형식입니다.",
  duplicationEmail: "* 이미 사용 중인 이메일 주소입니다.",
  duplicationMobile: "* 이미 사용 중인 휴대폰 번호입니다.",
  password: "비밀번호(영문/숫자/기호 포함 8자 이상)",
  newPassword: "새 비밀번호(영문/숫자/기호 포함 8자 이상)",
  incorrectPassword: "* 영문, 숫자, 특수문자를 조합해서 입력해주세요.",
  incorrectLimitPassword: "* 8~12자리로 입력해주세요.",
  passwordConfirm: "비밀번호 재입력",
  incorrectPasswordConfirm: "* 비밀번호를 다시 확인해주세요.",
  optionalInfo: "부가 정보를\n입력하세요",
  female: "여자",
  male: "남자",
  selectBirth: "생년월일 선택",
  optionalInfoDesc:
    "입력하신 성별/생년월일은 보다 나은 서비스를 위한 통계로\n활용됩니다.",
  complete: "회원가입 완료",
  completeMessage: "Tplus market의 다양한 서비스를 이용하실 수 있습니다.",
  goHome: "홈으로",
  businessAccount: "담당자 본인인증이\n필요합니다",
  businessAccountName: "담당자 이름 입력",
  companyCertification: "업체인증이\n필요합니다",
  companyName: "상호명",
  companyEmail: "이메일 주소",
  companyRegistrationNumber: "사업자 등록번호",
  registrationOfBusinessLicense: "사업자 등록증 등록",
  uploadFormatInfo: "PNG, JPG만 등록 가능합니다",
  BASignupComplete: "기업회원 가입완료",
  BASignupCompleteMessage:
    "가입 미승인 상태에서는 서비스가 제한됩니다\n승인기간은 약 1~2일 소요됩니다",
  tempPwd: "임시비밀번호 발급",
  tempPwdDesc: "휴대폰 번호로 임시 비밀번호를 전송했습니다",
  contact: "연락처 입력(-제외)",
  enterEmail: "이메일 주소 입력"
};

export const FindText = {};

export const MainText = {
  used: "중고",
  auctionTransaction: "경매 거래",
  usedGoods: "중고상품",
  newGoods: "새상품",
  permissionModalTitle: "앱 접근 권한 안내",
  permissionModalDesc:
    "원활한 서비스 사용을 위해\n다음 권한의 허용이 필요합니다.",
  accessRights: "접근 권한",
  optional: "(선택)",
  push: "푸시",
  pushDesc: "서비스 및 이벤트 알림",
  album: "앨범",
  camera: "카메라",
  cameraDesc: "피드 작성 및 프로필 변경",
  permissionModalDesc_2:
    "* 선택적 접근은 해당 기능을 사용할때 허용이 필요하며,\n비허용시에도 해당 기능 외 서비스 이용이 가능합니다.",
  companyCertificationCompleted: "업체 인증 완료",
  companyCertificationCompletedDesc:
    "업체 인증이 성공적으로 완료되어,\n티플러스 마켓의 모든 서비스 이용이 가능합니다. ",
};

export const StoreText = {
  used: "중고",
  goods: "상품 홈",
  usedGoods: "중고상품",
  newGoods: "새상품",
  releaseSchedule: "발매 일정",
  outOfStockProducts: "품절임박 상품",
  outOfStockMessage: "품절된 상품입니다.",
  outOfStockLimitMessage: "재고가 부족합니다.",
  stock: "재고",
  sale: "판매중",
  salesQuantity: "판매수량",
  won: "원",
  fromWon: "원부터",
  deadline: "마감",
  availableImmediatePurchase: "즉시구매 불가",
  auctionStartPrice: "경매시작가",
  whenPreOrder: "예약구매시",
  whenGroupBuying: "공동구매시",
  productInfo: "상세정보",
  immediatePurchasePrice: "즉시구매가",
  auctionStatus: "경매 현황",
  proceeding: "진행중",
  finishAuction: "입찰완료",
  latestBid: "최근 입찰가",
  pointsEarnedOnPurchases: "구매시 적립 포인트",
  auctionDeadline: "경매 마감일",
  biddingStatus: "입찰현황",
  biddingDate: "입찰일자",
  desiredBidPrice: "입찰희망가",
  count: "수량",
  biddingDesc: "재고수량에 해당되는 상위입찰자들 순서로 낙찰이 확정됩니다.",
  manufacturer: "제조사",
  manufactureNation: "제조국",
  manufactureManager: "A/S 책임자",
  manufactureQuality: "품질보증기능",
  modelNumber: "모델번호",
  releaseDate: "출시일",
  releasePrice: "발매가",
  shippingInformation: "배송안내",
  contactUs: "문의하기",
  relatedFeeds: "관련 피드",
  returnsAndRefunds: "반품 및 환불",
  disclosure: "상품정보 제공공시",
  buyNow: "즉시구매",
  toBid: "입찰하기",
  reBid: "재입찰하기",
  left: "남음",
  bidding: "입찰중",
  joining: "참여중",
  purchasePrice: "구매희망가",
  option: "옵션",
  secret: "비밀글입니다.",
  unanswered: "미답변",
  answerComplete: "답변완료",
  answer: "답변",
  seeMore: "더보기",
  toBeSold: "판매예정",
  notPurchase: "구매불가",
  jointPurchasePrice: "공동구매가",
  jointPurchaseStatus: "공동구매 현황",
  beforeSale: "판매전",
  finish: "마감",
  targetQuantity: "목표수량",
  groupPurchaseDeadline: "공동구매 마감일",
  groupPurchaseWarningMessage:
    "*마감일까지 수량 불충족시 거래가 자동파기됩니다.",
  groupPurcase: "공동구매",
  immediatePurchase: "즉시구매시",
  reservationPurchasePrice: "예약구매가",
  residualPayment: "잔여결제금",
  deposit: "예치금",
  depositDesc:
    "예치금은 예약상품을 구매하기 위한 보증금 개념으로 최종 상품가가 아닙니다. 예약구매 확정일에 잔여금을 결제해야합니다.",
  depositAucDesc:
      "예치금은 경매상품을 구매하기 위한 보증금 개념으로 최종 상품가가 아닙니다. 경매구매 확정일에 잔여금을 결제해야합니다.",
  reservationPurchaseStatus: "예약구매 현황",
  reservationPurchaseConfirmationDate: "예약구매 확정일",
  reservationPurchase: "예약구매",
  instantPurchaseStatus: "즉시구매 현황",
  salesClosingDate: "판매 마감일",
  selectOptions: "옵션선택",
  selectColor: "색상선택",
  selectCapacity: "용량선택",
  selectMoreOptions: "추가 옵션선택",
  noAdditionalOptions: "추가 옵션 없음",
  optional: "[선택]",
  next: "다음",
  orderNext: "주문하기",
  purchase: "상품구매",
  selectQuantity: "수량선택",
  transactionType: "거래유형",
  totalProduct: "상품합계",
  salesStatus: "판매현황",
  cart: "장바구니 담기",
  productPurchase: "결제하기",
  reservePurchase: "예약하기",
  productBidPrice: "상품입찰가",
  enterProductBidPrice: "상품입찰가 입력",
  auctionDeal: "경매거래",
  paymentOfBidDeposit: "입찰 예치금 결제",
  bidAmount: "입찰금액",
  minimumBidAmount: "최소 입찰금액",
  balance: "잔여금",
  previousBidAmount: "이전 입찰금액",
  reBidAmount: "재입찰금액",
  bidDeadline: "입찰 마감기한",
  auctionReBid: "경매 재입찰",
  depositPayment: "예치금결제",
  residualPaymentDate: "잔여금 결제일(구매확정일)",
  // totalProduct: "상품 합계",
  deadlineForJointPurchase: "공동구매 마감기한",
  // salesStatus: "판매현황",
  groupPurchaseDesc: "*마감일까지 목표수량 미달성시 결제금액은 환불처리됩니다.",
  deletePost: "게시글이 삭제되었습니다.",
  groupPurcaseTitle: "공동구매 상품 구매 시, 꼭 확인해주세요.",
  groupPurcaseMessage: "공동구매 상품은 결제취소가 불가해요.",
  groupPurcaseSubMessage:
    "- 공동구매 상품은 목표수량을 기준으로 거래가 성사되기 때문에, 중도포기(결제취소)가 불가합니다. 신중한 구매 부탁드립니다.",
  groupPurchaseModalWarningMessage:
    "* 공동구매 목표수량을 달성하지 못했을 경우, '공동구매 실패'로 처리되며 결제 금액 전체를 환불해드립니다.",
  groupPurchaseModalWarningMessage_2:
    "* 공동구매 성공 시 배송까지 모두 완료된 후 상품에 이상이 있을 경우, 교환 및 결제 금액 전체 환불이 가능합니다.",
  auctionPurchaseTitle: "경매거래 상품 구매 시, 꼭 확인해주세요.",
  auctionPurchaseMessage: "경매거래 상품은 중도 입찰 포기가 불가해요.",
  auctionPurchaseSubMessage:
    "- 경매거래 상품은 재입찰은 여러번 가능하나, 중도 입찰 포기(입찰예치금 결제취소)가 불가합니다. 신중한 구매 부탁드립니다.",
  auctionPurchaseWarningMessage:
    "* 경매거래 낙찰에 성공하지 못했을 경우, '입찰실패'로 처리되며 입찰 예치금 전체를 환불해드립니다.",
  auctionPurchaseWarningMessage_2:
    "* 경매거래 낙찰 성공 시 배송까지 모두 완료된 후 상품에 이상이 있을 경우, 교환 및 결제 금액(입찰예치금+입찰잔여금) 전체 환불이 가능합니다.",
  // auctionPurchaseWarningMessage_3:
  //   "* 재입찰을 여러 차례 진행하여 낙찰에 성공했을 경우, 낙찰건 이전의 입찰건에 대한 모든 입찰 예치금은 환불됩니다.",
  // auctionPurchaseWarningMessage_3:
  //     "* 입찰 희망 가격은 해당 상품 낙찰에 성공했을 경우에 입찰 예치금을 제외한 잔금으로 결제됩니다.\n* 경매거래 상품은 단일 옵션 판매로만 진행됩니다.",
  auctionPurchaseWarningMessage_3:
      "* 재입찰을 여러 차례 진행하실 경우, 예치금 결제는 없으며 기존 입찰건에서 입찰금액만 수정됩니다.",
  productInquiry: "상품 문의",
  add: "등록",
  inquiryPlaceholder: "문의하실 내용을 작성해주세요.",
  inquiryLimit: "문의 내용은 1,000자까지 입력 가능합니다.",
  inquiryMessage: "작성하신 문의글은 비공개 처리됩니다.",
  notice: "알림",
  noticeMessage: "상품문의가 등록되었습니다",
  onlyGeneral: "일반회원 전용상품",
  onlyGeneralMessage: "기업회원은 기업몰 상품만\n구매 가능합니다.",
  auctionDealMessage: "입찰은 최소 입찰금액보다 높은금액만 가능합니다",
  auctionLimitMessage: "입찰은 이전 입찰가보다 높은금액만 가능합니다",
  reAuctionDealMessage: "재입찰은 이전 입찰가보다 높은금액만 가능합니다",
  purchaseLimitMessage: "인당 구매 가능한 수량은",
  purchaseLimitMessage_2: "개 입니다.",
};

export const TicketText = {
  detail: "교환권 상세",
  sale: "판매중",
  immediatePurchasePrice: "즉시구매가",
  manufacturer: "제조사",
  modelNumber: "모델번호",
  releaseDate: "출시예정일",
  releasePrice: "발매가",
  dateOfPurchase: "구매일",
  productDetails: "상품상세",
  voucherSerialNumber: "교환권 시리얼 번호",
  serialNumber: "시리얼 번호",
  voucherValidityPeriod: "교환권 유효기간",
  productDescription: "상품설명",
  registrationDate: "등록일",
  seller: "판매자",
  paymentBalance: "결제 잔금",
  balancePaymentDate: "잔금 결제일",
  deleteMessage: "정말 삭제하시겠습니까?",
  no: "아니요",
  deleteConfirm: "네, 삭제할래요",
  editPost: "글 수정",
  deletePost: "글 삭제",
  salesClosingDate: "판매 마감일",
  purchase: "구매하기",
  share: "URL 공유",
  kakao: "카카오톡",
  band: "네이버밴드",
  url: "URL복사",
  ticketPurchase: "교환권 구매",
  purchaseVoucher: "구매 교환권",
  option: "옵션",
  validity: "유효기간",
  payerInformation: "결제자 정보",
  payment: "결제",
  point: "포인트",
  allUse: "모두사용",
  cancelUse: "사용취소",
  remainingPoints: "남은 포인트",
  voucherAmount: "교환권 금액",
  voucherBidAmount: "입찰 금액",
  redeemPoints: "포인트 사용",
  totalPaymentAmount: "총 결제금액",
  makeAPayment: "결제하기",
  leftover: "잔여",
  paymentFinished: "결제 완료",
  resultMessage: "회원님의 결제가 성공적으로 완료되었습니다.",
  purchaseHistory: "구매 내역 보러가기",
  voucherStoreHome: "교환권 스토어 홈으로",
  purchaseComplete: "거래완료",
  auctionInProgress: "경매진행중",
  toBid: "입찰하기",
  auctionLowestBid: "경매 최저입찰가",
  ticketBoardMessage: "최대 1,000자까지 입력 가능합니다.",
  refundInfoMessage: "정산계좌 정보가 필요합니다.",
  bidMessage: "* 희망가 상위입찰자들 순서로 낙찰이 확정됩니다.",
  auctionStatus: "경매 현황",
  proceeding: "진행중",
  finishAuc: "입찰완료",
  auctionDeadline: "경매 마감일",
  biddingStatus: "입찰현황",
  biddingDate: "입찰일자",
  purchasePrice: "구매희망가",
  latestBid: "최근 입찰가",
  voucherBid: "교환권 입찰",
  bidPrice: "입찰가",
  bidDeadline: "입찰 마감기한",
  auctionFinished: "경매 참여 완료",
  auctionResultMessage: "회원님의 교환권 경매거래 참여가 완료되었습니다.",
  transactionComplete: "거래 완료",
  deadline: "마감",
  transactionCompleteDesc: "거래가 완료되었습니다",
  rebidAndWaiver: "재입찰 및 포기",
  myBid: "내 입찰가",
  enterDesiredBid: "희망 입찰가 입력",
  previousBidAmount: "이전 입찰금액",
  reBidAmount: "재입찰가",
  waiverOfBid: "입찰포기",
  reBid: "재입찰하기",
  auctionLimitMessage: "입찰은 최저 입찰가보다 높은금액만 가능합니다",
  reAuctionLimitMessage: "재입찰은 이전 입찰가보다 높은금액만 가능합니다",
  bidAlertMessage: "정말 입찰을 포기하시겠어요?",
  waiverConfirm: "네, 포기할래요",
  bpModalTitle: "예약상품 잔금 결제일입니다.",
  bpModalDesc:
    "교환권 예약 상품의 잔금 결제일입니다.\n3일 이내 잔금을 꼭 결제해주세요.",
  bpModalBtn: "예약상품 잔금 결제하기",
  auctionModalMessage: "입찰 참여 감사드립니다.",
  auctionModalTicket: "교환권 낙찰에 성공하셨습니다.",
  auctionModalProduct: "상품 낙찰에 성공하셨습니다.",
  auctionModalProduct_2: "입찰 잔금을 결제해주세요",
  goToTheBidVouchder: "입찰 교환권 보러가기",
  goToTheBidProduct: "입찰 상품 보러가기",
  ticketSaleModalTitle: "교환권 판매시, 꼭 확인해주세요.",
  ticketSaleModalMessage: "정산금액은 실제 판매금액과 다를 수 있습니다.",
  ticketSaleModalSubMessage:
    "- 교환권 판매완료 시, 관리자 확인 후 등록하신 계좌로 부가세 및 수수료 5%를 제외한 금액이 정산됩니다.",
  ticketSaleModalWarningMessage:
    "* ex. 실제 판매금액이 50,000원이라면 최종 정산은 47,500원으로 계산",
  ticketSaleModalMessage_2: "꼭 본인명의의 계좌를 등록해주세요.",
  ticketSaleModalSubMessage_2:
    "- 계좌가 본인명의가 아닐 경우, 정산이 제한될 수 있습니다. 정산 처리 완료까지는 약 1~5일 정도 소요됩니다.",
  ticketSaleModalBtn: "위 내용을 이해했습니다.",
  selectTicketSale: "판매 교환권 선택",
  emptyText: "보유한 교환권이 없습니다!",
  next: "다음",
  saleInfoMessage: "* 교환권 판매는 한 번에 최대 1개씩만 등록 가능합니다.",
  writeSalesArticle: "판매글 작성",
  selectSalesMethod: "판매 방식 선택",
  selectSalesDeadline: "판매 마감일 선택",
  selectClosingTimeSale: "판매 마감시간 선택",
  price: "가격",
  lowPrice: "최저 입찰가격",
  enterContent: "내용을 입력하세요",
  settlementAccount: "정산계좌",
  ticketBoardInfoMessage:
    "- 정산 시 관리자 확인 후 등록하신 계좌로 부가세를 제외한 금액이 입금됩니다.",
  ticketBoardInfoMessage_2: "- 정산 처리는 영업일 기준 5일 정도 소요됩니다.",
  ticketBoardInfoMessage_3:
    "- 계좌가 본인명의가 아닐 경우, 정산이 제한될 수 있습니다.",
  finishedAppointment: "등록완료",
  boardAucDateMessage: "유효기간 이전의 날짜를 선택해주세요.",
  writeCancel: "작성 취소",
  editInfo: "정보변경",
  buyNow: "즉시구매",
  auctionDeal: "경매거래",
  selectComplete: "선택완료",
  ticketBoardConfirmMessage: "이미 구매완료 및 구매 진행중인 상품으로\n글 수정/삭제가 불가합니다."
};

export const SearchText = {
  searchTitle: "어떤 상품을\n찾고 계신가요?",
  placeholder: "검색어를 입력하세요",
  latestSearchText: "최근 검색어",
  allDelete: "전체삭제",
  allSearch: "통합검색",
  product: "상품",
  ticket: "교환권",
  tag: "태그",
  post: "게시물",
  follower: "구독자",
  all: "전체",
  buyNow: "즉시구매",
  auctionDeal: "경매거래",
  buyReserve: "예약구매",
  groupPurchase: "공동구매",
  usedGoods: "중고상품",
  newGoods: "새상품",
  business: "기업mall",
  selling: "판매중",
  used: "중고",
  empty: "해당 검색어의 검색 결과가 없습니다",
};

export const CartText = {
  cart: "장바구니",
  infoMessage: "장바구니 이용은 즉시구매 상품만 가능합니다.",
  infoMessage_2: "- 즉시구매 상품만 장바구니 이용 및 일괄 결제가 가능합니다.",
  infoMessage_3: "- 경매거래, 예약구매, 공동구매 등은 바로 결제만 가능합니다.",
  allSelect: "전체선택",
  selectDelete: "선택삭제",
  soldOutDelete: "품절삭제",
  totalPrice: "총 상품금액",
  deliveryFee: "배송비",
  free: "무료",
  purchasePrice: "예상 결제 금액",
  purchase: "결제하기",
  soldOut: "품절",
};

export const PaymentText = {
  deletePayment: "주문서 생성에 실패했습니다.",
  productPurchase: "상품구매",
  buyNow: "즉시거래",
  buyBid: "경매거래",
  buyGroup: "공동거래",
  buyReserve: "예약구매",
  orderProduct: "주문 상품",
  paymentBalance: "결제 잔금",
  fold: "접기",
  open: "펼치기",
  infomationChange: "정보변경",
  ordererInformation: "결제자 정보",
  directDepositRefundAccount: "무통장입금 환불 계좌",
  payment: "결제",
  point: "포인트",
  useAll: "모두사용",
  useCancel: "사용취소",
  leftover: "잔여",
  totalProductAmount: "총 상품금액",
  redeemPoints: "포인트 사용",
  shippingFee: "배송비",
  totalPaymentAmount: "총 결제금액",
  free: "무료",
  purchase: "결제하기",
  option: "옵션",
  quantity: "수량",
  purchaseProduct: "결제 상품",
  deposit: "예치금",
  refundAccount: "환불 계좌",
  productBid: "상품 입찰가",
  bidDeposit: "입찰예치금",
  productPrice: "상품가",
  reservationDeposit: "예약예치금",
  balancePayment: "잔금결제",
  paymentMethod: "결제수단",
  directDeposit: "무통장입금",
  cardPayment: "카드결제",
  depositor: "입금자명 입력",
  depositorMessage:
    "실제 입금자명과 다른 경우 입금 확인이 불가하니, 입금자명을 정확하게 입력해주세요.",
  easyPayment: "간편결제",
  cashReceiptRequest: "현금영수증 신청",
  forProofOfExpenses: "지출증빙용",
  notApplied: "미신청",
  businessNumber: "사업자번호 숫자만 입력",
  shippingInformation: "배송지 정보",
  shippingInfoPlaceholder: "배송 시 요청사항을 입력해주세요.",
  goToHome: "상품 스토어 홈으로",
  auctionFinished: "경매 참여 완료",
  paymentFail: "결제 실패",
  paymentFailMessage: "주문 결제를 실패하였습니다.\n고객센터로 문의해주세요",
  auctionFinishedMessage: "회원님의 경매거래 참여가 완료되었습니다.",
  resultMessage: "회원님의 결제가 성공적으로 완료되었습니다.",
  purchaseHistory: "구매 내역 보러가기",
  reserveFinised: "상품 예약 완료",
  reserveFinisedMessage: "회원님의 예약구매 상품 예약이 완료되었습니다.",
  purchaseComplete: "결제 완료",
  purchaseCompleteMessage: "회원님의 주문이 성공적으로 완료되었습니다.",
  expectedPaymentAmount: "결제 예정 금액",
  accountHolder: "예금주",
  depositBank: "입금은행",
  depositAccount: "입금계좌",
  depositDeadline: "입금기한",
  amountOfPayment: "결제금액",
  orderStatus: "주문상태",
  orderDate: "주문일자",
  productAmount: "상품금액",
  refundInfoMessage: "입력하지 않으셔도 결제가 가능합니다.",
  naverPay: "네이버페이",
  kakaoPay: "카카오페이"
};

export const NotificationText = {
  noti: "알림",
  notiLinkError: "링크 정보가 정확하지 않습니다.",
};

export const TagText = {
  popularity: "인기",
  subscribe: "구독",
  subscribing: "구독중",
  notice: "알림",
  alertMessage: "최소 구매이력 1회가 필요합니다.",
  post: "게시물",
  subscriber: "구독자",
  moreInfo: "상세정보",
  editPost: "글 수정",
  deletePost: "글 삭제",
  report: "신고",
  reportIt: "신고하기",
  reportMessage: "신고 항목을 선택해주세요.",
  reportPlaceholder: "상세한 설명이 추가로 필요한 경우에만 작성(최대 500자)",
  reportErrorMessage: "최대 500자까지 작성 가능합니다.",
  reportComplete: "신고완료",
  reportCompleteMessage: "신고가 접수되었습니다. 감사합니다.",
  like: "좋아요",
  addFeed: "피드등록",
  updateFeed: "피드수정",
  addPhoto: "사진추가",
  feedPlaceholder: "피드 내용을 입력하세요",
  add: "등록",
  edit: "수정",
  relatedTag: "관련태그",
  addTag: "태그추가",
  relatedProducts: "연관상품",
  searchPlaceholder: "모델명이나 제품명을 검색",
  youtubeUrl: "유튜브 URL",
  addLink: "링크입력",
  album: "앨범",
  trendProduct: "트렌드 상품",
  searchTag: "태그명 검색",
  popularTags: "실시간 인기태그",
  representative: "대표",
  otherFeed: "님의 또다른 피드",
  productFeed: "상품 관련 피드",
};

export const MyPageText = {
  feed: "피드",
  purchase: "구매",
  sale: "판매",
  email: "이메일",
  point: "나의 포인트",
  productInquiry: "상품 문의",
  cart: "장바구니(즉시구매 전용)",
  account: "계좌 설정",
  password: "비밀번호 설정",
  logout: "로그아웃",
  faq: "FAQ",
  notice: "공지사항",
  qna: "1:1문의",
  qnaDetail: "1:1 문의글 남기기",
  qnaDetailInfo: "운영시간 : 9:00 ~ 18:00 (토,일,공휴일 제외)",
  privacyPolicy: "개인정보처리방침",
  term: "이용약관",
  myInfoEdit: "내 정보 변경",
  serviceCenter: "고객센터",
  selectPhoto: "사진선택",
  takePhoto: "사진찍기",
  getPhoto: "앨범에서 사진선택",
  setting: "설정",
  newVersion: "최신버전",
  currentVersion: "현재버전",
  csCallNum: "대표전화: 1533-5040",
  cacheRemove: "캐시삭제",
  cacheUse: "사용",
  pushNLanguage: "푸쉬알림 및 언어설정",
  setLanguage: "언어설정",
  korean: "한국어",
  pushNotice: "푸쉬 알림",
  pushNoticeMessage: "모든 소식을 받아볼 수 있습니다.",
  myFeed: "마이 피드",
  write: "작성",
  editPost: "글 수정",
  deletePost: "글 삭제",
  writeQna: "1:1 문의 작성",
  inquiryType: "문의유형",
  inquiryTypePlaceholder: "문의유형을 선택하세요",
  inquiries: "문의내용",
  inquiryTitle: "제목을 입력하세요(최대 20자)",
  inquiryPlaceholder: "문의 내용을 입력하세요.",
  addPhoto: "사진추가",
  photoMessage: "*이미지는 최대 4개까지 첨부 가능합니다.",
  photoMessage_1: "*이미지는 최대 ",
  photoMessage_2: "4개까지 첨부 가능합니다.",
  addInquiry: "문의 등록",
  noticeDetail: "공지 상세",
  defaultAddress: "기본 배송지 설정",
  defaultAddressModal: "배송지 설정 완료",
  defaultAddressComplete: "회원님의 기본 배송지\n설정이 완료되었습니다.",
  addressLimitModal: "배송지 설정",
  addressLimitMessage: "기본 배송지 설정은\n5개까지만 가능합니다.",
  defaultAccountModal: "환불계좌 설정 완료",
  defaultAccountComplete: "회원님의 환불계좌\n설정이 완료되었습니다.",
  addAddress: "추가",
  addressSetting: "주소 설정",
  shippingAddress: "배송지 입력",
  searchAddress: "우편번호 검색",
  addShippingAddressComplete: "배송지 입력완료",
  accountSetting: "계좌 설정",
  passwordSetting: "비밀번호 설정",
  subscriptionList: "구독 리스트",
  representative: "대표",
  myProductInquiry: "나의 상품문의 내역",
  all: "전체",
  answer: "답변",
  unanswered: "미답변",
  answerComplete: "답변완료",
  mySale: "판매내역",
  myPoint: "포인트 내역",
  accumulate: "적립",
  deduction: "차감",
  eventConditions: "참여 조건",
  eventPoint: "참여 차감 포인트",
  logoutTitle: "로그아웃 하시겠습니까?",
  logoutMessage: "로그아웃 하시면 서비스 이용과\n푸쉬알림 이용이 불가합니다.",
  logoutConfirm: "네, 로그아웃 할래요.",
  withdrawTitle: "회원탈퇴시\n안내사항을 꼭 확인해주세요.",
  withdrawMessage_1:
    "회원탈퇴 시 개인정보 및 이용기록은 모두 삭제되며, 삭제된 계정은 복구할 수 없습니다.",
  withdrawMessage_2:
    "(단, 관련 법령에 의거하여 일정기간 동안 개인정보를 보유할 필요가 있을 경우 법이 정한 기간동안 개인정보를 처리 및 보유합니다.)",
  withdrawMessage_3:
    "또한, 앱 활동 시 적립된 포인트는 미정산 상태로 탈퇴할 시에 모두 소멸되며, 소멸된 포인트는 복구할 수 없습니다.",
  withdraw: "회원탈퇴",
  agree: "모든 정보를 삭제하는 것에 동의합니다.",
  completeWithdraw: "회원탈퇴 완료",
  completeWithdrawMessage: "회원탈퇴가 성공적으로 완료되었습니다.",
  goToHome: "메인 홈으로",
  myBuy: "구매내역",
  productPurchase: "상품구매",
  ticketPurchase: "교환권구매",
  proceeding: "진행중",
  completion: "완료",
  exchange: "교환/반품/환불",
  ticketExchange: "사용/환불",
  setContactInfo: "담당자 정보 설정",
  updateSubmit: "변경 완료",
  taxInvoiceApplication: "세금계산서 신청",
  passwordChangeInquiry: "비밀번호 변경 문의",
  businessUserTerms: "사업자회원이용약관",
  contactUsTitle: "고객센터에\n연결하시겠습니까?",
  compamyCallTitle: "대표전화에\n연결하시겠습니까?",
  contactCall: "연결하기",
  taxApplication: "기업 세금계산서 신청",
  notApplied: "미신청",
  completeApplied: "신청완료(발행대기)",
  published: "발행완료",
  taxApplicationBtn: "세금계산서 신청하기",
  taxApplicationModalTitle: "세금계산서 신청완료",
  taxApplicationFail: "세금계산서 신청 불가",
  taxFailMessage1: "회원님은 현재 사업자 ",
  taxFailMessage2: "미승인",
  taxFailMessage3: " 상태로,\n세금계산서 신청이 불가합니다.",
  taxApplicationModalDesc:
    "세금계산서는 회원가입시\n입력하신 이메일로 전송됩니다.",
  processingStatus: "처리현황",
  applicationDate: "신청일자",
  issueDate: "발행처리일시",
  ordererInformation: "결제자 정보",
  paymentInfo: "결제 정보",
  paymentMethod: "결제방법",
  totalPaymentAmount: "총 결제금액",
  details: "내역 상세",
  productBid: "상품 입찰가",
  reservDeposit: "예약예치금",
  bidDeposit: "입찰예치금",
  redeemPoints: "포인트 사용",
  ticketInfo: "교환권 정보",
  cancelDetail: "취소상세",
  paymentCancel: "결제 취소하기",
  paymentCancelDetail: "결제취소 상세",
  refundInfo: "환불정보",
  productPrice: "상품 금액",
  discountPrice: "할인 금액",
  deliveryFee: "배송비차감액",
  refundPoint: "포인트 사용 환불",
  expectedRefundAmount: "환불예정금액",
  confirmationOfPurchase: "구매확정",
  returnRequest: "반품요청",
  returnRequestDetail: "반품요청 상세",
  exchangeRequest: "교환요청",
  exchangeRequestDetail: "교환요청 상세",
  deliveryTracking: "배송조회",
  shippingInfo: "배송지정보",
  recipient: "받는분",
  address: "주소",
  contact: "연락처",
  orderer: "결제자",
  courier: "택배사",
  invoiceNumber: "송장번호",
  completeDelivery: "배송완료",
  exchangeRequestTitle: "교환사유 및 교환 상품 정보 입력",
  exchangeRequestPlaceholder: "교환 사유 및 교환하실 상품을 입력해주세요.",
  withdrawalOfRequest: "요청 철회",
  notWithdrawalOfRequest: "요청 철회 불가",
  reasonForReturn: "반품사유",
  reasonForReturnDesc: "사유를 선택하세요",
  returnRequestPlaceholder: "(선택) 내용을 입력하세요.",
  returnRequestSuccess: "반품요청 완료",
  returnRequestMessage:
    "회원님의 반품요청이 완료되었습니다.\n확인까지 1~3일 소요될 수 있습니다.",
  goToMyBuy: "구매내역으로",
  seeMore: "상세",
  dlvyModalMessage: "배송이 완료되었을 때,\n교환/반품 요청이 가능합니다.",
  calcelConfirmModalTitle: "결제 취소 하시겠습니까?",
  calcelConfirmModalMessage:
    "결제 취소 시, 모든 상품이\n결제 취소 단계로 변경됩니다.",
  calcelConfirmModalBtn: "네, 취소할래요.",
  confirmModalTitle: "구매 확정을 진행하시겠습니까?",
  confirmModalBtn: "네, 구매 확정할래요.",
  returnRequestModalTitle: "요청을 철회하시겠습니까?",
  returnRequestModalMessage:
    "요청 철회시, 자동으로 상품\n구매확정 단계로 변경됩니다.",
  returnRequestModalBtn: "네, 철회할래요.",
  writeFeed: "피드 작성하기",
  wroteFeed: "피드 작성완료",
  finishAuction: "입찰완료",
  biddingDeadline: "입찰마감일",
  productDetail: "상품상세",
  productDetailBtn: "상품상세 보러가기",
  serialNum: "교환권 시리얼 번호",
  ticketExpDates: "교환권 유효기간",
  payTheBalance: "잔금 결제하기",
  payTheBalanceComplete: "잔금 결제완료",
  outstanding: "미결제",
  paymentDate: "결제일",
  purchaseComplete: "거래완료",
  failBidding: "입찰실패",
  lastUpdate: "최근 업데이트",
  selectLanguage: "언어선택",
  selectComplete: "선택완료",
};

export const MyBuyText = {
  orderNo: "주문번호",
  checkMessage1: "꼭 확인해주세요.",
  checkMessage2: "- 배송 상품의 모든 문의는 관리자가 답변해 드립니다.",
  checkMessage3: "- 상품 교환/환불 시, 하단 요청 버튼을 통해 진행해주세요.",

}

//////////////// code ////////////////
export const CodeText = {
  mber_se_cd_g: "MSC00001", // 일반회원
  mber_se_cd_c: "MSC00002", // 기업회원
  sex_cd_m: "SC000001", // 남성
  sex_cd_w: "SC000002", // 여성
  mber_img_typ_cd_p: "MITC0001", // 프로필사진
  mber_img_typ_cd_r: "MITC0002", // 사업자등록증
  goods_se_cd_n: "GSC00001", // 새상품
  goods_se_cd_r: "GSC00002", // 중고상품
  sale_mth_cd_r: "SMC00004", // 예약구매
  sale_mth_cd_a: "SMC00002", // 경매거래
  sale_mth_cd_i: "SMC00001", // 즉시구매
  sale_mth_cd_g: "SMC00003", // 공동구매
  os_cd_android: "OC000001", // 안드로이드
  os_cd_ios: "OC000002", // iOS
  goods_cntnts_cd_v: "GCTC0001", // 상품 > 동영상
  goods_cntnts_cd_t: "GCTC0002", // 상품 > 썸네일
  goods_cntnts_cd_d: "GCTC0003", // 상품 > 상세이미지
  goods_cntnts_cd_c: "GCTC0004", // 상품 > 첨부파일

  pay_dtl_typ_cd_c: "PDTC0001", // 결제 수단 : 카드
  pay_dtl_typ_cd_p: "PDTC0003", // 결제 수단 : 포인트 사용
  pay_dtl_typ_cd_n: "PDTC0002", // 결제 수단 : 무통장 입금

  auc_trd_sts_cd_s: "ATSC0003", // 입찰 성공
  auc_trd_sts_cd_f: "ATSC0004", // 입찰 실패
  auc_trd_sts_cd_r: "ATSC0008", // 입찰 잔여금 결제

  reserv_purchase_sts_cd_s: "RPSC0004", // 예약확정 > 잔여금액결제 대기
  reserv_purchase_sts_cd_f: "RPSC0003", // 예약 > 구매포기
  reserv_purchase_sts_cd_r: "RPSC0005", // 예약 > 잔여금액결제완료

  refund_cd_submit: "IPODRSC1", // 반품요청
  refund_cd_submit_l: "LPORSC01", // 반품요청 : 경매,예약,공동
  exchng_cd_submit: "IPODESC1", // 교환요청
  exchng_cd_c: "IPODESC5", // 교환요청 철회
  ord_dtl_sts_cd_p: "IPODSC02", // 결제완료
  dlvy_sts_cd_s: "DSC00003", // 배송완료

  /* 2차 개발 코드*/
  exchng_vol_trd_typ_cd_i: "EVTTC001", // 즉시구매
  exchng_vol_trd_typ_cd_a: "EVTTC002", // 경매거래
};

export const AppScr = {
  main: "20211009005155DBBCNH", // 메인화면
};

//////////////// iamport ////////////////
export const iamportKey = {
  scheme: "iamportsvcorpscelere",
  imp: "imp08107453",
  key: "3950308722159185",
  secret:
    "1af40b22ab0a74564cfd892c0bf308ed1cde6ac0cba7fee6e34ed1ff80d5454c08ee01659aad73dc",
};

export const BillingMethod = {
  trans: {
    key: "trans",
    pg: "danal_tpay",
    method: "trans",
    locale: "계좌이체",
  },
  card: { key: "card", pg: "danal_tpay", method: "card", locale: "카드" },
  bank: { key: "bank", pg: "danal_tpay", method: "vbank", locale: "무통장" },
  kakao: { key: "kakao", pg: "kakaopay", method: "card", locale: "카카오페이" },
  naver: { key: "naver", pg: "naverpay", method: "card", locale: "네이버페이" },
  payco: { key: "payco", pg: "payco", method: "card", locale: "페이코" },
};
