import { StyleSheet } from "react-native";
import Fonts from "../../model/lib/Utils/Fonts";
import Colors from "../../model/lib/Utils/Colors";
import {DEVICE_WIDTH} from "../../model/lib/Utils/Constants";

const styles = StyleSheet.create({
  rowCenter: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
  },
  betweenCenter: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  container: {
    flex: 1,
    backgroundColor: "white",
  },
  submitBox: {
    height: 60,
    alignItems: "center",
    justifyContent: "center",
    width: "100%",
    backgroundColor: "#000000",
  },
  submit: {
    fontFamily: Fonts.AppleR,
    fontSize: 20,
    color: "#f5f5f5",
  },
  title: {
    fontFamily: Fonts.AppleB,
    fontSize: 18,
    letterSpacing: -0.9,
    color: "#000000",
  },
  fold: {
    fontFamily: Fonts.AppleR,
    letterSpacing: -0.35,
    color: "#000000",
    textDecorationLine: "underline",
  },
  cardOrderProduct: {
    marginTop: 24.2,
    paddingBottom: 12.5,
    borderBottomColor: "#dddddd",
    borderBottomWidth: 1,
  },
  orderProduct: {
    marginTop: 22,
    paddingBottom: 2.5,
    borderBottomColor: "#dddddd",
    borderBottomWidth: 1,
  },
  productBox: {
    padding: 10,
    borderRadius: 5,
    backgroundColor: "#f9f9f9",
    flexDirection: "row",
    marginBottom: 17.5,
    width: "100%",
  },
  purchaseTypeBox: {
    borderTopLeftRadius: 5,
    backgroundColor: "rgba(0,0,0,0.5)",
    flexDirection: "row",
    paddingHorizontal: 5,
    paddingVertical: 2.5,
    // width: 50,
    position: "absolute",
    top: 10,
    left: 10,
    zIndex: 5,
  },
  purchaseType: {
    fontFamily: Fonts.AppleR,
    fontSize: 12,
    letterSpacing: -0.6,
    color: "#ffffff",
  },
  productImg: {
    height: 80,
    aspectRatio: 1,
    borderRadius: 5,
    backgroundColor: "#e1e1e1",
    marginRight: 15,
    resizeMode: "contain",
  },
  productTitle: {
    fontFamily: Fonts.AppleB,
    fontSize: 13,
    letterSpacing: -0.33,
    color: "#222222",
    width: DEVICE_WIDTH - 95 - 60,
  },
  productPrice: {
    fontFamily: Fonts.AppleB,
    fontSize: 15,
    letterSpacing: -0.38,
    color: "#222222",
  },
  productOption: {
    fontFamily: Fonts.AppleR,
    fontSize: 12,
    letterSpacing: -0.3,
    color: "#777777",
    marginTop: 4.5,
  },
  productQuantity: {
    fontFamily: Fonts.AppleR,
    fontSize: 12,
    letterSpacing: -0.3,
    color: "#777777",
    marginTop: 1,
  },
  infomationChange: {
    fontFamily: Fonts.AppleR,
    letterSpacing: -0.35,
    color: Colors.MAIN_COLOR,
    textDecorationLine: "underline",
  },
  infoBox: {
    paddingVertical: 20,
    borderBottomColor: "#dddddd",
    borderBottomWidth: 1,
  },
  name: {
    fontFamily: Fonts.AppleR,
    letterSpacing: -0.35,
    color: "#222222",
    marginTop: 16,
  },
  address: {
    fontFamily: Fonts.AppleR,
    letterSpacing: -0.35,
    color: "#222222",
  },
  orderOptionBox: {
    height: 45,
    borderRadius: 5,
    borderStyle: "solid",
    borderWidth: 1,
    borderColor: "#999999",
    alignItems: "center",
    justifyContent: "space-between",
    flexDirection: "row",
    paddingHorizontal: 15,
    marginTop: 15,
  },
  orderOption: {
    fontFamily: Fonts.AppleR,
    fontSize: 15,
    letterSpacing: -0.38,
    color: "#222222",
  },
  account: {
    fontFamily: Fonts.AppleR,
    letterSpacing: -0.35,
    color: "#222222",
  },
  textForm: {
    fontFamily: Fonts.AppleR,
    letterSpacing: -0.35,
    color: "#222222",
    padding: 0,
  },
  paymentInfoTitle: {
    fontFamily: Fonts.AppleR,
    fontSize: 13,
    letterSpacing: -0.33,
    color: "#999999",
  },
  paymentInfoDesc: {
    fontFamily: Fonts.AppleB,
    letterSpacing: -0.35,
    color: "#222222",
    textAlign: "right",
  },
  paymentAmountTitle: {
    fontFamily: Fonts.AppleB,
    fontSize: 18,
    letterSpacing: -0.45,
    color: "#000000",
  },
  paymentAmount: {
    fontFamily: Fonts.AppleB,
    fontSize: 18,
    letterSpacing: -0.45,
    color: Colors.MAIN_COLOR,
  },
  purchaseBox: {
    height: 40,
    borderBottomWidth: 0.5,
    borderBottomColor: "#222222",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    width: "70%",
    marginRight: 20,
  },
  point: {
    fontFamily: Fonts.AppleR,
    letterSpacing: -0.35,
    color: "#222222",
  },
  pointBox: {
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "center",
    height: 40,
    paddingTop: 5,
  },
  useBtn: {
    flex: 1,
    height: 40,
    borderRadius: 5,
    backgroundColor: "#ffffff",
    borderWidth: 1,
    borderColor: "#999999",
    alignItems: "center",
    justifyContent: "center",
    // width: "25%",
  },
  leftoverPoint: {
    fontFamily: Fonts.AppleR,
    letterSpacing: -0.35,
    color: "#222222",
    marginTop: 10,
  },
  useBtnText: {
    fontFamily: Fonts.AppleB,
    letterSpacing: -0.35,
    color: "#222222",
  },
  totalPayment: {
    paddingTop: 20,
    borderTopColor: "#dddddd",
    borderTopWidth: 1,
    marginTop: 20,
  },
  depositorBox: {
    marginTop: 5,
    borderRadius: 5,
    borderWidth: 1,
    borderColor: "#dddddd",
    height: 45,
    justifyContent: "center",
    paddingLeft: 15,
  },
  depositorMessage: {
    fontFamily: Fonts.AppleR,
    fontSize: 13,
    letterSpacing: -0.33,
    color: "#999999",
    marginTop: 10,
    lineHeight: 20.5,
  },
  shippingOptionBox: {
    width: "100%",
    backgroundColor: "white",
    position: "absolute",
    top: 157,
    left: 0,
    zIndex: 200,
    borderWidth: 1,
    borderColor: "#999999",
    borderTopWidth: 0,
    paddingTop: 7.5,
    paddingBottom: 12,
    borderBottomLeftRadius: 5,
    borderBottomRightRadius: 5,
  },
  shippingOptionWrap: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 5,
    paddingLeft: 15,
    zIndex: 10,
  },
  shippingOptionTitle: {
    fontSize: 15,
    letterSpacing: -0.38,
    marginRight: 7.5,
  },
  shippingOptionInput: {
    marginTop: 17,
    justifyContent: "center",
    borderBottomColor: "#222222",
    borderBottomWidth: 0.5,
    height: 35,
  },
  productPriceWrap: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: 4,
  },
  depositText: {
    marginLeft: 5,
    fontFamily: Fonts.AppleR,
    fontSize: 11,
    letterSpacing: -0.28,
    color: Colors.MAIN_COLOR,
  },
  pointLeft: {
    fontFamily: Fonts.AppleR,
    letterSpacing: -0.35,
    color: "#222222",
  },
  paymentOtherText: {
    fontFamily: Fonts.AppleR,
    fontSize: 13,
    letterSpacing: -0.33,
    color: "#595959",
  },
  paymentOtherPrice: {
    fontFamily: Fonts.AppleB,
    letterSpacing: -0.35,
    color: "#595959",
  },
  accountBox: {
    width: "100%",
    backgroundColor: "white",
    position: "absolute",
    // top: 218, // 간편결제 있을 때
    left: 0,
    zIndex: 200,
    borderWidth: 1,
    borderColor: "#999999",
    borderTopWidth: 0,
    paddingTop: 7.5,
    paddingBottom: 12,
    borderBottomLeftRadius: 5,
    borderBottomRightRadius: 5,
  },
  accountBoxWrap: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 5,
    paddingLeft: 15,
  },
  accountBoxText: {
    fontSize: 15,
    letterSpacing: -0.38,
    marginRight: 7.5,
  },
  cashReceiptText: {
    fontFamily: Fonts.AppleR,
    fontSize: 13,
    letterSpacing: -0.33,
    color: "#999999",
    marginBottom: 2,
  },
  easyPaymentBox: {
    width: "100%",
    backgroundColor: "white",
    borderWidth: 1,
    borderColor: "#999999",
    borderTopWidth: 0,
    paddingTop: 7.5,
    paddingBottom: 12,
    borderBottomLeftRadius: 5,
    borderBottomRightRadius: 5,
  },
  easyPayment: {
    fontFamily: Fonts.AppleR,
    fontSize: 15,
    letterSpacing: -0.38,
    color: "#999999",
  },
});

export default styles;
