export default {
  ////////////// eCOMM_CD /////////////
  eCOMM_CD: "/eCOMM_CD",
  eAPP_VER: "/eAPP_VER",
  eHDLVY_CMPNY: "/eHDLVY_CMPNY",

  ////////////// eSESSION /////////////
  eSESSION: "/eSESSION",

  ////////////// eFILE /////////////
  eFILE_UPLOAD: "/eFILE_UPLOAD",
  eFILE_IMAGE_UPLOAD: "/eFILE_IMAGE_UPLOAD",

  ////////////// eMBER /////////////
  eMBER_LOGIN: "/eMBER_LOGIN",
  eMBER_LOGIN_SOCIAL: "/eMBER_LOGIN_SOCIAL",
  eMBER_CHECK_EMAIL: "/eMBER_CHECK_EMAIL",
  eMBER_CHECK_MOBLPHON: "/eMBER_CHECK_MOBLPHON",
  eMBER_CHECK_ALEADY_EXIST: "/eMBER_CHECK_ALEADY_EXIST",
  eMBER_DETAIL: "/eMBER_DETAIL",
  eMBER_USER_CREATE: "/eMBER_USER_CREATE",
  eMBER_USER_UPDATE: "/eMBER_USER_UPDATE",
  eMBER_USER_DELETE: "/eMBER_USER_DELETE",
  eMBER_IMG_USER_CREATE: "/eMBER_IMG_USER_CREATE",
  eMBER_IMG_USER_UPDATE: "/eMBER_IMG_USER_UPDATE",
  eMBER_CONN_USER_CREATE: "/eMBER_CONN_USER_CREATE", // 화면 접속 시, 통계 자료
  eMBER_CONN_USER_UPDATE: "/eMBER_CONN_USER_UPDATE", // 화면 접속 시, 통계 자료
  eMBER_FIND_ID: "/eMBER_FIND_ID",
  eMBER_FIND_PASSWORD_MSC00001: "/eMBER_FIND_PASSWORD_MSC00001",
  eMBER_FIND_PASSWORD_MSC00002: "/eMBER_FIND_PASSWORD_MSC00002",

  ////////////// eUSER /////////////
  eUSER_LOGIN: "/eUSER_LOGIN",
  eUSER_LOGOUT: "/eUSER_LOGOUT",
  eVERFI_SMS_CREATE: "/eVERFI_SMS_CREATE",
  eVERFI_SMS_CHECK: "/eVERFI_SMS_CHECK",
  eUSER_LOGIN_SOCIAL: "/eUSER_LOGIN_SOCIAL",

  ////////////// eUSE_STPLAT /////////////
  eUSE_STPLAT_USER_DETAIL: "/eUSE_STPLAT_USER_DETAIL",

  ////////////// eFAQ /////////////
  eFAQ_CTGRY_USER_LIST: "/eFAQ_CTGRY_USER_LIST",
  eFAQ_USER_LIST: "/eFAQ_USER_LIST",

  ////////////// eNOTICE_MATTER /////////////
  eNOTICE_MATTER_USER_LIST: "/eNOTICE_MATTER_USER_LIST",
  eNOTICE_MATTER_USER_DETAIL: "/eNOTICE_MATTER_USER_DETAIL",

  ////////////// eBANNER /////////////
  eBANNER_USER_LIST: "/eBANNER_USER_LIST",
  eBANNER_USER_VIEW_UPDATE: "/eBANNER_USER_VIEW_UPDATE",

  ////////////// eEVENT /////////////
  eEVENT_USER_DETAIL: "/eEVENT_USER_DETAIL",
  eEVENT_USER_OPEN: "/eEVENT_USER_OPEN",

  ////////////// eONETOONE_INQRY /////////////
  eONETOONE_INQRY_USER_CREATE: "/eONETOONE_INQRY_USER_CREATE",
  eONETOONE_INQRY_USER_UPDATE: "/eONETOONE_INQRY_USER_UPDATE",
  eONETOONE_INQRY_USER_DELETE: "/eONETOONE_INQRY_USER_DELETE",
  eONETOONE_INQRY_IMG_USER_CREATE: "/eONETOONE_INQRY_IMG_USER_CREATE",
  eONETOONE_INQRY_IMG_USER_UPDATE: "/eONETOONE_INQRY_IMG_USER_UPDATE",
  eONETOONE_INQRY_USER_LIST: "/eONETOONE_INQRY_USER_LIST",
  eONETOONE_INQRY_USER_DETAIL: "/eONETOONE_INQRY_USER_DETAIL",

  ////////////// eACCOUNT_DELIVERY /////////////
  eACCOUNT_DELIVERY_USER_CREATE: "/eACCOUNT_DELIVERY_USER_CREATE",
  eACCOUNT_DELIVERY_USER_UPDATE: "/eACCOUNT_DELIVERY_USER_UPDATE",
  eACCOUNT_DELIVERY_USER_DELETE: "/eACCOUNT_DELIVERY_USER_DELETE",
  eACCOUNT_DELIVERY_USER_LIST: "/eACCOUNT_DELIVERY_USER_LIST",
  eACCOUNT_DELIVERY_USER_DETAIL: "/eACCOUNT_DELIVERY_USER_DETAIL",
  eDLVY_USER_REFRESH: "/eDLVY_USER_REFRESH", // 주문서 > 배송 정보 업데이트

  ////////////// eGOODS_INQRY /////////////
  eGOODS_INQRY_USER_CREATE: "/eGOODS_INQRY_USER_CREATE",
  eGOODS_INQRY_USER_DELETE: "/eGOODS_INQRY_USER_DELETE",
  eGOODS_INQRY_USER_UPDATE: "/eGOODS_INQRY_USER_UPDATE",
  eGOODS_INQRY_USER_LIST: "/eGOODS_INQRY_USER_LIST",
  eGOODS_INQRY_USER_DETAIL: "/eGOODS_INQRY_USER_DETAIL",

  ////////////// eTAG /////////////
  eTAG_USER_LIST: "/eTAG_USER_LIST",
  eTAG_USER_DETAIL: "/eTAG_USER_DETAIL",
  eTAG_USER_NTT_LIST: "/eTAG_USER_NTT_LIST",
  eTAG_USER_SBSCRB_LIST: "/eTAG_USER_SBSCRB_LIST",
  eTAG_SBSCRB_USER_CLICK: "/eTAG_SBSCRB_USER_CLICK",

  ////////////// eNTT /////////////
  eNTT_USER_CREATE: "/eNTT_USER_CREATE",
  eNTT_USER_UPDATE: "/eNTT_USER_UPDATE",
  eNTT_USER_DELETE: "/eNTT_USER_DELETE",
  eNTT_TAG_USER_CREATE: "/eNTT_TAG_USER_CREATE",
  eNTT_TAG_USER_DELETE: "/eNTT_TAG_USER_DELETE",
  eNTT_IMG_USER_CREATE: "/eNTT_IMG_USER_CREATE",
  eNTT_IMG_USER_DELETE: "/eNTT_IMG_USER_DELETE",
  eNTT_STTEMNT_USER_CREATE: "/eNTT_STTEMNT_USER_CREATE",
  eNTT_LIKE_USER_CLICK: "/eNTT_LIKE_USER_CLICK",
  eNTT_USER_LIST: "/eNTT_USER_LIST",
  eNTT_USER_DETAIL: "/eNTT_USER_DETAIL",
  eNTT_USER_LIKE_LIST: "/eNTT_USER_LIKE_LIST",
  eNTT_USER_SBSCRB_LIST: "/eNTT_USER_SBSCRB_LIST",

  ////////////// eGOODS /////////////
  eGOODS_USER_MAIN_LIST: "/eGOODS_USER_MAIN_LIST",
  eGOODS_USER_STORE_LIST: "/eGOODS_USER_STORE_LIST",
  eGOODS_USER_STORE_DETAIL: "/eGOODS_USER_STORE_DETAIL",
  eGOODS_USER_SEARCH_LIST: "/eGOODS_USER_SEARCH_LIST",
  eGOODS_USER_STORE_MAIN_LIST: "/eGOODS_USER_STORE_MAIN_LIST",

  ////////////// eBASKET /////////////
  eBASKET_DTL_USER_CREATE: "/eBASKET_DTL_USER_CREATE", // 장바구니 추가
  eBASKET_DTL_ADD_OPTN_USER_CREATE: "/eBASKET_DTL_ADD_OPTN_USER_CREATE", // 장바구니 추가할 때, 추가옵션 선택한 것을 추가하는 부분
  eBASKET_DTL_USER_UPDATE: "/eBASKET_DTL_USER_UPDATE", // 장바구니 수량변경
  eBASKET_DTL_USER_DELETE: "/eBASKET_DTL_USER_DELETE", // 장바구니 삭제 (add_optn은 이거 삭제하면 자동으로 함께 삭제됨)
  eBASKET_DTL_USER_LIST: "/eBASKET_DTL_USER_LIST", // 장바구니 목록

  ////////////// eIMMEDI_PURCHASE /////////////
  eIMMEDI_PURCHASE_USER_CREATE: "/eIMMEDI_PURCHASE_USER_CREATE", // 즉시구매주문 생성
  eIMMEDI_PURCHASE_DTL_USER_CREATE: "/eIMMEDI_PURCHASE_DTL_USER_CREATE", // 즉시구매주문 주문상세내역 생성
  eIMMEDI_PURCHASE_DTL_ADD_OPTN_USER_CREATE: "/eIMMEDI_PURCHASE_DTL_ADD_OPTN_USER_CREATE", // 즉시구매주문 주문상세내역의 추가옵션 생성
  eIMMEDI_PURCHASE_USER_DELETE: "/eIMMEDI_PURCHASE_USER_DELETE", // 즉시구매주문 삭제
  eIMMEDI_PURCHASE_USER_DETAIL: "/eIMMEDI_PURCHASE_USER_DETAIL", // 상품정보, 결제정보, 배송지정보, 무통장계좌 등을 내려주겠습니다.
  eIMMEDI_PURCHASE_USER_ORDER_CANC: "/eIMMEDI_PURCHASE_USER_ORDER_CANC", // 결제취소
  eIMMEDI_PURCHASE_DTL_USER_ORDER_CONFIRM: "/eIMMEDI_PURCHASE_DTL_USER_ORDER_CONFIRM", // 구매확정
  eIMMEDI_PURCHASE_DTL_USER_ORDER_RTNGUD: "/eIMMEDI_PURCHASE_DTL_USER_ORDER_RTNGUD", // 반품(환불)요청
  eIMMEDI_PURCHASE_DTL_USER_ORDER_RTNGUD_CANCEL: "/eIMMEDI_PURCHASE_DTL_USER_ORDER_RTNGUD_CANCEL", // 반품(환불)요청 취소
  eIMMEDI_PURCHASE_DTL_USER_ORDER_EXCHNG: "/eIMMEDI_PURCHASE_DTL_USER_ORDER_EXCHNG", // 교환요청
  eIMMEDI_PURCHASE_DTL_USER_ORDER_EXCHNG_CANCEL: "/eIMMEDI_PURCHASE_DTL_USER_ORDER_EXCHNG_CANCEL", // 교환요청 취소

  ////////////// eREFUND_MN : 환불계좌 /////////////
  eREFUND_MN_USER_DETAIL: "/eREFUND_MN_USER_DETAIL",
  eREFUND_MN_USER_CREATE: "/eREFUND_MN_USER_CREATE",
  eREFUND_MN_USER_UPDATE: "/eREFUND_MN_USER_UPDATE",

  ////////////// eNBKK_RCPMNY_ACCNT : 무통장입금 목록 /////////////
  eNBKK_RCPMNY_ACCNT_USER_LIST: "/eNBKK_RCPMNY_ACCNT_USER_LIST",
  eNBKK_RCPMNY_ACCNT_USER_DETAIL: "/eNBKK_RCPMNY_ACCNT_USER_DETAIL",

  ////////////// eAUC_TRD : 경매구매 /////////////
  eAUC_TRD_USER_CREATE: "/eAUC_TRD_USER_CREATE", // 입찰하기
  eAUC_TRD_USER_RE_BID: "/eAUC_TRD_USER_RE_BID", // 재입찰하기
  eAUC_TRD_USER_DETAIL: "/eAUC_TRD_USER_DETAIL", // 구매내역 > 경매거래

  ////////////// eCOPERTN_PURCHASE : 공동구매 /////////////
  eCOPERTN_PURCHASE_USER_CREATE: "/eCOPERTN_PURCHASE_USER_CREATE",
  eCOPERTN_PURCHASE_USER_DETAIL: "/eCOPERTN_PURCHASE_USER_DETAIL",

  ////////////// eRESERV_PURCHASE : 예약구매 /////////////
  eRESERV_PURCHASE_USER_CREATE: "/eRESERV_PURCHASE_USER_CREATE",
  eRESERV_PURCHASE_ADD_OPTN_USER_CREATE: "/eRESERV_PURCHASE_ADD_OPTN_USER_CREATE",
  eRESERV_PURCHASE_USER_DETAIL: "/eRESERV_PURCHASE_USER_DETAIL",

  ////////////// ePAYMENT : 임시 API /////////////
  ePAYMENT_USER_TEMP_AUC_DPST_SUCCESS: "/ePAYMENT_USER_TEMP_AUC_DPST_SUCCESS", // (임시)경매거래 : 결제
  ePAYMENT_USER_AUC_DPST_POINT: "/ePAYMENT_USER_AUC_DPST_POINT", // 경매거래 : 포인트 처리
  ePAYMENT_USER_AUC_REMAIN_POINT: "/ePAYMENT_USER_AUC_REMAIN_POINT", // 경매거래 : 잔금결제 시, 포인트 처리
  ePAYMENT_USER_TEMP_AUC_REMAIN_SUCCESS: "/ePAYMENT_USER_TEMP_AUC_REMAIN_SUCCESS", // (임시)경매거래 : 잔금결제 시, 포인트 처리
  ePAYMENT_USER_AUC_REMAIN_TRANSFER: "/ePAYMENT_USER_AUC_REMAIN_TRANSFER", // 경매거래 : 무통장입금 정보 업데이트

  ePAYMENT_USER_TEMP_COPERTN_PURCHASE_SUCCESS: "/ePAYMENT_USER_TEMP_COPERTN_PURCHASE_SUCCESS", // (임시)공동구매 : 결제
  ePAYMENT_USER_COPERTN_PURCHASE_POINT: "/ePAYMENT_USER_COPERTN_PURCHASE_POINT", // 공동구매 : 포인트 처리

  ePAYMENT_USER_TEMP_IMMEDI_SUCCESS: "/ePAYMENT_USER_TEMP_IMMEDI_SUCCESS", // (임시)즉시거래 : 결제
  ePAYMENT_USER_IMMEDI_PURCHASE_POINT: "/ePAYMENT_USER_IMMEDI_PURCHASE_POINT", // 즉시거래 : 포인트 처리
  ePAYMENT_USER_IMMEDI_PURCHASE_TRANSFER: "/ePAYMENT_USER_IMMEDI_PURCHASE_TRANSFER", // 즉시거래 : 무통장입금 정보 업데이트

  ePAYMENT_USER_RESERV_DPST_POINT: "/ePAYMENT_USER_RESERV_DPST_POINT",
  ePAYMENT_USER_RESERV_REMAIN_POINT: "/ePAYMENT_USER_RESERV_REMAIN_POINT",
  ePAYMENT_USER_RESERV_REMAIN_TRANSFER: "/ePAYMENT_USER_RESERV_REMAIN_TRANSFER", // 예약거래 : 무통장입금 정보 업데이트

  ePAYMENT_USER_AUC_DPST_AVAILABLE: "/ePAYMENT_USER_AUC_DPST_AVAILABLE",
  ePAYMENT_USER_AUC_REMAIN_AVAILABLE: "/ePAYMENT_USER_AUC_REMAIN_AVAILABLE",
  ePAYMENT_USER_RESERV_DPST_AVAILABLE: "/ePAYMENT_USER_RESERV_DPST_AVAILABLE",
  ePAYMENT_USER_RESERV_REMAIN_AVAILABLE: "/ePAYMENT_USER_RESERV_REMAIN_AVAILABLE",
  ePAYMENT_USER_COPERTN_PURCHASE_AVAILABLE: "/ePAYMENT_USER_COPERTN_PURCHASE_AVAILABLE",
  ePAYMENT_USER_IMMEDI_PURCHASE_AVAILABLE: "/ePAYMENT_USER_IMMEDI_PURCHASE_AVAILABLE",

  ////////////// eLAST_PURCHASE /////////////
  eLAST_PURCHASE_USER_ORDER_CONFIRM: "/eCOPERTN_PURCHASE_USER_CREATE", // 경매, 공구, 예약의 '구매확정'
  eLAST_PURCHASE_USER_ORDER_EXCHNG: "/eLAST_PURCHASE_USER_ORDER_EXCHNG", // 경매, 공구, 예약의 '교환신청'
  eLAST_PURCHASE_USER_ORDER_RTNGUD: "/eLAST_PURCHASE_USER_ORDER_RTNGUD", // 경매, 공구, 예약의 '반품(환불)신청'
  eLAST_PURCHASE_USER_ORDER_EXCHNG_CANCEL: "/eLAST_PURCHASE_USER_ORDER_EXCHNG_CANCEL", // 경매, 공구, 예약의 '교환신청 취소'
  eLAST_PURCHASE_USER_ORDER_RTNGUD_CANCEL: "/eLAST_PURCHASE_USER_ORDER_RTNGUD_CANCEL", // 경매, 공구, 예약의 '반품(환불)신청 취소'

  ////////////// eSRCHWRD /////////////
  eSRCHWRD_MBER_USER_LIST: "/eSRCHWRD_MBER_USER_LIST",
  eSRCHWRD_MBER_USER_CREATE: "/eSRCHWRD_MBER_USER_CREATE",
  eSRCHWRD_MBER_USER_DELETE: "/eSRCHWRD_MBER_USER_DELETE",
  eSRCHWRD_DD_SUM_USER_LIST: "/eSRCHWRD_DD_SUM_USER_LIST", // 트렌드상품

  ////////////// eORDER /////////////
  eORDER_USER_COUNT: "/eORDER_USER_COUNT", // 구매내역 상품 개수
  eORDER_USER_LIST: "/eORDER_USER_LIST", // 구매내역

  ////////////// eTAX_BILL /////////////
  eTAX_BILL_USER_LIST: "/eTAX_BILL_USER_LIST",
  eTAX_BILL_USER_COUNT: "/eTAX_BILL_USER_COUNT",
  eTAX_BILL_USER_CREATE: "/eTAX_BILL_USER_CREATE",

  ////////////// ePNT /////////////
  ePNT_ACCML_USER_LIST: "/ePNT_ACCML_USER_LIST",
  ePNT_USE_USER_LIST: "/ePNT_USE_USER_LIST",

  ////////////// ePUSH /////////////
  ePUSH_USER_LIST: "/ePUSH_USER_LIST",
  ePUSH_USER_NEW: "/ePUSH_USER_NEW",
  ePUSH_USER_READ: "/ePUSH_USER_READ",

  ////////////// eEXCHNG_VOL /////////////
  eEXCHNG_VOL_USER_LIST: "/eEXCHNG_VOL_USER_LIST", // 사용자 보유 교환권 목록
  eEXCHNG_VOL_TRD_USER_CREATE: "/eEXCHNG_VOL_TRD_USER_CREATE", // 사용자 교환권 거래 생성
  eEXCHNG_VOL_TRD_USER_UPDATE: "/eEXCHNG_VOL_TRD_USER_UPDATE", // 사용자 교환권 거래 수정
  eEXCHNG_VOL_TRD_USER_DELETE: "/eEXCHNG_VOL_TRD_USER_DELETE", // 사용자 교환권 거래 삭제
  eEXCHNG_VOL_USER_STORE_USE: "/eEXCHNG_VOL_USER_STORE_USE", // 사용자 교환권 거래 스토어 공개여부/상세/목록
  eEXCHNG_VOL_TRD_USER_DETAIL: "/eEXCHNG_VOL_TRD_USER_DETAIL",
  eEXCHNG_VOL_TRD_USER_STORE_LIST: "/eEXCHNG_VOL_TRD_USER_STORE_LIST",
  eEXCHNG_VOL_TRD_USER_LIST: "/eEXCHNG_VOL_TRD_USER_LIST", // 사용자 교환권 판매 목록
  eEXCHNG_VOL_TRD_USER_SHARE: "/eEXCHNG_VOL_TRD_USER_SHARE", // 사용자 교환권 판매 공유 횟수 증가
  eEXCHNG_VOL_AUC_TRD_USER_LIST: "/eEXCHNG_VOL_AUC_TRD_USER_LIST", // 사용자 교환권 경매 거래 목록
  eEXCHNG_VOL_AUC_TRD_USER_CREATE: "/eEXCHNG_VOL_AUC_TRD_USER_CREATE", // 사용자 교환권 경매 거래 입찰
  eEXCHNG_VOL_TRD_USER_ORDER_COUNT: "/eEXCHNG_VOL_TRD_USER_ORDER_COUNT",
  eEXCHNG_VOL_TRD_USER_ORDER_LIST: "/eEXCHNG_VOL_TRD_USER_ORDER_LIST",
  eEXCHNG_VOL_AUC_TRD_USER_BID_ABAND: "/eEXCHNG_VOL_AUC_TRD_USER_BID_ABAND", // 사용자 교환권 경매 입찰 포기
  eEXCHNG_VOL_AUC_TRD_USER_DETAIL: "/eEXCHNG_VOL_AUC_TRD_USER_DETAIL", // 사용자 교환권 경매거래 입찰 상세

  ePAYMENT_USER_EXCHNG_VOL_IMMEDI_POINT: "/ePAYMENT_USER_EXCHNG_VOL_IMMEDI_POINT", // 교환권 즉시구매 포인트
  ePAYMENT_USER_EXCHNG_VOL_IMMEDI_AVAILABLE: "/ePAYMENT_USER_EXCHNG_VOL_IMMEDI_AVAILABLE", // 교환권 즉시구매 포인트 사용가능
  ePAYMENT_USER_EXCHNG_VOL_AUC_TRD_POINT: "/ePAYMENT_USER_EXCHNG_VOL_AUC_TRD_POINT", // 교환권 경매구매 포인트
  ePAYMENT_USER_EXCHNG_VOL_AUC_TRD_AVAILABLE: "/ePAYMENT_USER_EXCHNG_VOL_AUC_TRD_AVAILABLE", // 교환권 경매구매 포인트 사용가능

};


const apiUrl = {
  'development': 'http://192.168.1.2:3000/api/v1', // localhost
  'dev_server': 'http://dev.tplusshop.com/api/v1', // dev_server & dev DB : http://13.124.6.33/
  'production': 'https://api.tplusshop.com/api/v1', // 상용
  'deliverytrack': 'https://apis.tracker.delivery/carriers',
};

export {apiUrl};
